const fs = require('fs');
const P = 'D:/qwen-bridge/src/index.ts';
let c = fs.readFileSync(P, 'utf8');

console.log('=== Phase 1: Fix Emoji Encoding ===');

// Fix \U0001fXXXX → literal emoji (these are NOT valid JS escapes, they render as literal "U0001f...")
const emojiMap = {
  '\\U0001f4ca': '📊',
  '\\U0001f4c8': '📈',
  '\\U0001f4cb': '📋',
  '\\U0001f465': '👥',
  '\\U0001f9e0': '🧠',
  '\\U0001f517': '🔗',
  '\\U0001f4a1': '💡',
};
for (const [esc, emoji] of Object.entries(emojiMap)) {
  const count = (c.match(new RegExp(esc.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')) || []).length;
  if (count > 0) {
    c = c.split(esc).join(emoji);
    console.log(`  Replaced ${count}x ${esc} → ${emoji}`);
  }
}

console.log('\n=== Phase 2: Version Unification ===');

// Add getVersion function before "const server = new Server"
const serverMarker = '// ─── MCP Server ───────────────────────────────────────────────────────────────\nconst server = new Server(';
const getVersionBlock = `function getVersion(): string {
  try {
    const pkgPath = path.join(__dirname, '..', 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    return pkg.version || '5.5.0';
  } catch {
    return '5.5.0';
  }
}

// ─── MCP Server ───────────────────────────────────────────────────────────────
const server = new Server(`;

if (c.includes(serverMarker) && !c.includes('function getVersion()')) {
  c = c.replace(serverMarker, getVersionBlock);
  console.log('  Added getVersion() function');
}

// Fix server version string
if (c.includes("{ name: 'autoclaude', version: '5.3.0' }")) {
  c = c.replace("{ name: 'autoclaude', version: '5.3.0' }", "{ name: 'autoclaude', version: getVersion() }");
  console.log('  Fixed server creation to use getVersion()');
}

// Fix qwen_bridge_status banner: 'AutoClaude v5.3 — Status' → use template literal
// The line is: '\u2502' + padStr('              AutoClaude v5.3 \u2014 Status               ', W) + '\u2502'
// Change to:    '\u2502' + padStr(\`              AutoClaude v\${getVersion()} \u2014 Status               \`, W) + '\u2502'
const oldStatus = "'\\u2502' + padStr('              AutoClaude v5.3 \\u2014 Status               ', W) + '\\u2502'";
const newStatus = "'\\u2502' + padStr(`              AutoClaude v${'{getVersion()}'()} \\u2014 Status               `, W) + '\\u2502'";
if (c.includes(oldStatus)) {
  c = c.replace(oldStatus, newStatus);
  console.log('  Fixed status banner');
} else {
  // Fallback: just replace the text portion
  c = c.replace('AutoClaude v5.3 \\u2014 Status', 'AutoClaude v${getVersion()} \\u2014 Status');
  console.log('  Fixed status banner (fallback)');
}

// Fix finalizeTaskSummary footer: v5.3 → v${getVersion()}
if (c.includes('Report generated by AutoClaude v5.3')) {
  c = c.replace('Report generated by AutoClaude v5.3', 'Report generated by AutoClaude v${getVersion()}');
  console.log('  Fixed finalizeTaskSummary footer');
}

// Fix updateProjectReport footer: lines.push('*AutoClaude v5.3*')
if (c.includes("lines.push('*AutoClaude v5.3*')")) {
  c = c.replace("lines.push('*AutoClaude v5.3*')", "lines.push('*AutoClaude v' + getVersion() + '*')");
  console.log('  Fixed project report footer');
}

console.log('\n=== Phase 3: Polling-based Finalize ===');

// 3a. In get_task_report handler: add more aggressive finalize check
// Find the auto-finalize block in get_task_report and enhance it
const oldFinalizeBlock = `    // Auto-finalize: if result log has content, finalize the summary
    if (fs.existsSync(summaryPath) && fs.existsSync(resultLog)) {
      const resultStat = fs.statSync(resultLog);
      const hasContent = resultStat.size > 10;
      const summary = fs.readFileSync(summaryPath, 'utf-8');
      const notFinalized = !summary.includes('Completion Status') && !summary.includes('Token Economics');

      if (hasContent && notFinalized) {
        try {
          const taskContent = fs.existsSync(taskPath) ? fs.readFileSync(taskPath, 'utf-8') : '';
          const agentMatch = summary.match(/\\*\\*Agent\\*\\* \\| (.+?) \\|/);
          const agentLabel = agentMatch ? agentMatch[1] : 'Agent';
          finalizeTaskSummary(summaryPath, taskPath, new Date(resultStat.mtime), true, taskContent, agentLabel);
        } catch (e) {
          try {
            const bt = String.fromCharCode(96);
            const footer = '\\n\\n---\\n\\n## Completion Status\\n\\n| Status | \\u2705 Completed |\\n| Result Log | ' + bt + path.basename(resultLog) + bt + ' |\\n\\n*Report auto-finalized by get_task_report.*\\n';
            fs.appendFileSync(summaryPath, footer, 'utf-8');
          } catch {}
        }
        try { updateProjectReport(); } catch {}
      }
    }`;

const newFinalizeBlock = `    // Auto-finalize: if result log has content, finalize the summary
    if (fs.existsSync(summaryPath) && fs.existsSync(resultLog)) {
      const resultStat = fs.statSync(resultLog);
      const hasContent = resultStat.size > 10;
      let summary = fs.readFileSync(summaryPath, 'utf-8');
      const notFinalized = !summary.includes('Completion Status') && !summary.includes('Token Economics');

      if (hasContent && notFinalized) {
        try {
          const taskContent = fs.existsSync(taskPath) ? fs.readFileSync(taskPath, 'utf-8') : '';
          const agentMatch = summary.match(/\\*\\*Agent\\*\\* \\| (.+?) \\|/);
          const agentLabel = agentMatch ? agentMatch[1] : 'Agent';
          finalizeTaskSummary(summaryPath, taskPath, new Date(resultStat.mtime), true, taskContent, agentLabel);
          // Re-read after auto-finalize
          summary = fs.existsSync(summaryPath) ? fs.readFileSync(summaryPath, 'utf-8') : summary;
        } catch (e) {
          try {
            const bt = String.fromCharCode(96);
            const footer = '\\n\\n---\\n\\n## Completion Status\\n\\n| Status | \\u2705 Completed |\\n| Result Log | ' + bt + path.basename(resultLog) + bt + ' |\\n\\n*Report auto-finalized by get_task_report.*\\n';
            fs.appendFileSync(summaryPath, footer, 'utf-8');
          } catch {}
        }
        try { updateProjectReport(); } catch {}
      }
    }`;

if (c.includes('Auto-finalize: if result log has content')) {
  // Replace the block - the key change is re-reading summary after finalize
  c = c.replace(
    'const summary = fs.readFileSync(summaryPath, \'utf-8\');',
    'let summary = fs.readFileSync(summaryPath, \'utf-8\');'
  );
  // Add re-read after finalize
  c = c.replace(
    'finalizeTaskSummary(summaryPath, taskPath, new Date(resultStat.mtime), true, taskContent, agentLabel);\n        } catch (e) {',
    'finalizeTaskSummary(summaryPath, taskPath, new Date(resultStat.mtime), true, taskContent, agentLabel);\n          // Re-read after auto-finalize\n          summary = fs.existsSync(summaryPath) ? fs.readFileSync(summaryPath, \'utf-8\') : summary;\n        } catch (e) {'
  );
  console.log('  Enhanced get_task_report auto-finalize');
}

// 3b. In get_project_report handler: scan for unfinalized summaries before reading report
const oldProjectReport = `  // -- get_project_report -----------------------------------------------------
  if (request.params.name === 'get_project_report') {
    const reportPath = path.join(config.projectDir, 'PROJECT_REPORT.md');
    if (!fs.existsSync(reportPath)) {
      updateProjectReport();
    }
    const report = fs.readFileSync(reportPath, 'utf-8');
    return {
      content: [{ type: 'text' as const, text: report }],
    };
  }`;

const newProjectReport = `  // -- get_project_report -----------------------------------------------------
  if (request.params.name === 'get_project_report') {
    const projectDir = config.projectDir;
    // Scan for unfinalized summaries and finalize them
    try {
      const files = fs.readdirSync(projectDir);
      for (const f of files) {
        if (f.startsWith('QWEN_') && f.endsWith('_summary.md')) {
          const summaryPath = path.join(projectDir, f);
          const summary = fs.readFileSync(summaryPath, 'utf-8');
          if (!summary.includes('Completion Status') && !summary.includes('Token Economics')) {
            const taskFile = f.replace('_summary.md', '.md');
            const taskPath = path.join(projectDir, taskFile);
            const resultLog = f.replace('_summary.md', '_result.log');
            const resultPath = path.join(projectDir, resultLog);
            if (fs.existsSync(resultPath) && fs.statSync(resultPath).size > 10) {
              try {
                const taskContent = fs.existsSync(taskPath) ? fs.readFileSync(taskPath, 'utf-8') : '';
                finalizeTaskSummary(summaryPath, taskPath, new Date(), true, taskContent);
              } catch {}
            }
          }
        }
      }
    } catch {}
    const reportPath = path.join(projectDir, 'PROJECT_REPORT.md');
    updateProjectReport();
    const report = fs.readFileSync(reportPath, 'utf-8');
    return {
      content: [{ type: 'text' as const, text: report }],
    };
  }`;

if (c.includes('// -- get_project_report') && !c.includes('Scan for unfinalized summaries')) {
  c = c.replace(
    `  if (request.params.name === 'get_project_report') {
    const reportPath = path.join(config.projectDir, 'PROJECT_REPORT.md');
    if (!fs.existsSync(reportPath)) {
      updateProjectReport();
    }
    const report = fs.readFileSync(reportPath, 'utf-8');
    return {
      content: [{ type: 'text' as const, text: report }],
    };
  }`,
    newProjectReport.split('\n').map(l => l.replace(/^  /, '')).join('\n').replace(/^  /, '').trimStart()
  );
  // Actually let me do this more carefully - replace the exact block
  c = c.replace(
    /if \(request\.params\.name === 'get_project_report'\) \{[\s\S]*?content: \[\{ type: 'text' as const, text: report \}\],[\s\S]*?\};[\s\S]*?\}/,
    `if (request.params.name === 'get_project_report') {
    const projectDir = config.projectDir;
    // Scan for unfinalized summaries and finalize them
    try {
      const files = fs.readdirSync(projectDir);
      for (const f of files) {
        if (f.startsWith('QWEN_') && f.endsWith('_summary.md')) {
          const summaryPath = path.join(projectDir, f);
          const summary = fs.readFileSync(summaryPath, 'utf-8');
          if (!summary.includes('Completion Status') && !summary.includes('Token Economics')) {
            const taskFile = f.replace('_summary.md', '.md');
            const taskPath = path.join(projectDir, taskFile);
            const resultLog = f.replace('_summary.md', '_result.log');
            const resultPath = path.join(projectDir, resultLog);
            if (fs.existsSync(resultPath) && fs.statSync(resultPath).size > 10) {
              try {
                const taskContent = fs.existsSync(taskPath) ? fs.readFileSync(taskPath, 'utf-8') : '';
                finalizeTaskSummary(summaryPath, taskPath, new Date(), true, taskContent);
              } catch {}
            }
          }
        }
      }
    } catch {}
    const reportPath = path.join(projectDir, 'PROJECT_REPORT.md');
    updateProjectReport();
    const report = fs.readFileSync(reportPath, 'utf-8');
    return {
      content: [{ type: 'text' as const, text: report }],
    };
  }`
  );
  console.log('  Added unfinalized scan to get_project_report');
}

// ─── Write ─────────────────────────────────────────────────────────────────
fs.writeFileSync(P, c, 'utf8');
console.log('\n✅ All phases applied to src/index.ts');

// ─── Verify ────────────────────────────────────────────────────────────────
const L = c.split('\n');
console.log('\nVerification:');
console.log('  Emoji: no U0001f escapes:', !c.includes('\\U0001f'));
console.log('  getVersion() exists:', c.includes('function getVersion()'));
console.log('  server uses getVersion():', c.includes('version: getVersion()'));
console.log('  No hardcoded 5.3.0:', !c.includes("'5.3.0'"));
console.log('  get_project_report scans:', c.includes('Scan for unfinalized summaries'));

// Show any remaining v5.3
let hasV53 = false;
L.forEach((line, i) => {
  if (line.includes('v5.3') && !line.includes('getVersion')) {
    console.log('  ⚠️  Still has v5.3 at line', i+1);
    hasV53 = true;
  }
});
if (!hasV53) console.log('  No remaining hardcoded v5.3');
