const fs = require('fs');
const P = 'D:/qwen-bridge/src/index.ts';
let c = fs.readFileSync(P, 'utf8');

// ─── Phase 2: Version ──────────────────────────────────────────────────────

// Add getVersion before "const server = new Server"
c = c.replace(
  'const server = new Server(',
  `function getVersion(): string {
  try {
    const pkgPath = path.join(__dirname, '..', 'package.json');
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    return pkg.version || '5.5.0';
  } catch {
    return '5.5.0';
  }
}

// ─── MCP Server ───────────────────────────────────────────────────────────────
const server = new Server(`
);

// Remove the duplicate comment that was before server
c = c.replace(/\/\/ ─── MCP Server ───────────────────────────────────────────────────────────────\n\/\/ ─── MCP Server/g, '// ─── MCP Server');

// Fix server version
c = c.replace("{ name: 'autoclaude', version: '5.3.0' }", "{ name: 'autoclaude', version: getVersion() }");

// Fix status banner line (find by content, replace v5.3 with getVersion)
c = c.replace(/AutoClaude v5\.3 \\u2014 Status/g, 'AutoClaude v${getVersion()} \\u2014 Status');
// Fix the quoting: the line uses single quotes, needs to be a template literal
c = c.replace(/'\\u2502' \+ padStr\(`AutoClaude v\$\{getVersion\(\)\}/g, "`\\u2502` + padStr(`AutoClaude v${getVersion()}");

// Actually let me just do a simpler find-and-replace on the key strings
// Reset and do it cleanly:
c = c.replace(/AutoClaude v5\.3 \\u2014 Status/g, 'AutoClaude v${getVersion()} \\u2014 Status');

// Fix finalizeTaskSummary footer
c = c.replace(/Report generated by AutoClaude v5\.3/g, 'Report generated by AutoClaude v${getVersion()}');

// Fix updateProjectReport footer
c = c.replace(/\*AutoClaude v5\.3\*/g, "*AutoClaude v" + "getVersion() + " + "*");
// Fix: lines.push('*AutoClaude v5.3*')  →  lines.push('*AutoClaude v' + getVersion() + '*')  
c = c.replace(
  "lines.push('*AutoClaude v5.3*')",
  "lines.push('*AutoClaude v' + getVersion() + '*')"
);

fs.writeFileSync(P, c, 'utf8');
console.log('Phase 2 done');

// Verify
const L = c.split('\n');
console.log('getVersion exists:', c.includes('function getVersion()'));
console.log('server uses getVersion:', c.includes('version: getVersion()'));
console.log('5.3.0 gone:', !c.includes("'5.3.0'"));

// Show any remaining v5.3
L.forEach((line, i) => { if (line.includes('v5.3')) console.log('Still has v5.3 at line', i+1, ':', line.trim().substring(0, 80)); });
